const PROJECTS = [
  {
    id: "nyc311",
    title: "NYC 311 Complaint Analytics",
    type: "da",
    typeLabel: "Data Analysis · ML",
    date: "2026",
    thumb: "thumb-blue",
    thumbIcon: "🗽",
    thumbLabel: "dbt · DuckDB · XGBoost",
    desc: "End-to-end analytics platform on 499K+ NYC 311 service requests — geospatial heatmaps, Prophet forecasting, XGBoost classification, and a multi-turn LLM Text-to-SQL agent.",
    tags: ["Python", "dbt", "DuckDB", "XGBoost", "LLaMA 3.1", "Streamlit"],
    links: { demo: "https://nyc311-analytics-jfan.streamlit.app/", github: "https://github.com/jfan4926" },
    metrics: [
      { key: "Records", val: "499K+" },
      { key: "XGBoost AUC", val: "0.96" },
      { key: "Forecast Horizon", val: "4 months" },
    ],
    detail: {
      overview: "A full-stack analytics platform built on NYC open data, covering the complete journey from raw ingestion to an interactive Streamlit app. Combines classical ML, time series forecasting, and a conversational AI agent in a single deployment.",
      highlights: [
        "dbt staging-to-marts architecture on DuckDB with automated data quality tests",
        "Interactive geospatial heatmap of complaint density across NYC boroughs",
        "Prophet time series model forecasting 4-month complaint volumes by category",
        "XGBoost classifier (AUC = 0.96) with Optuna tuning, MLflow tracking, Evidently drift monitoring, and SHAP waterfall charts for per-prediction explainability",
        "Similar historical case lookup for real-world context alongside each prediction",
        "Multi-turn LLM Text-to-SQL agent (LLaMA 3.1 · Groq · RAG) with conversation history and follow-up question support",
        "GitHub Actions CI/CD running automated dbt tests and ruff linting on every push",
      ],
      techDetail: "dbt handles all transformations on a DuckDB file — staging models clean raw CSVs, mart models aggregate KPIs. The ML pipeline (XGBoost + Optuna + MLflow) runs independently and persists artifacts for the Streamlit app to load. LLM agent uses RAG over schema docs to translate natural language to SQL at query time.",
    },
  },
  {
    id: "ecommerce",
    title: "E-Commerce Analytics & AI Insights",
    type: "bi",
    typeLabel: "BI / Dashboard · AI",
    date: "2026",
    thumb: "thumb-indigo",
    thumbIcon: "🛒",
    thumbLabel: "Azure · Power BI · Claude",
    desc: "End-to-end analytics pipeline on 100K+ orders — Azure cloud stack, Power BI & Tableau dashboards, Claude API sentiment analysis, and Bayesian A/B testing.",
    tags: ["Python", "SQL", "Azure", "Power BI", "Tableau", "Claude API"],
    links: { demo: "https://e-commerce-analytics-jfan.streamlit.app/", github: "https://github.com/jfan4926" },
    metrics: [
      { key: "GMV Tracked", val: "$15.4M" },
      { key: "Orders", val: "100K+" },
      { key: "Reviews Analyzed", val: "4,500+" },
    ],
    detail: {
      overview: "A cloud-native analytics pipeline for a Brazilian e-commerce dataset, spanning data ingestion through executive dashboards and AI-powered insights. Built to mirror a real-world enterprise BI stack.",
      highlights: [
        "Azure Blob Storage + Azure SQL + star schema data model as the cloud foundation",
        "Power BI dashboards with DAX-based KPI tracking: GMV, delivery SLA, regional satisfaction",
        "Tableau geospatial analysis of customer distribution and regional performance trends",
        "Claude API integration for multilingual review classification and sentiment analysis across 4,500+ Portuguese reviews",
        "Bayesian A/B testing engine using Monte Carlo simulation (50K+ samples) to measure delivery speed impact on satisfaction",
        "Conversational Text-to-SQL AI agent deployed via Streamlit Cloud with GitHub Actions and pytest automation",
      ],
      techDetail: "Data flows from Azure Blob → Azure SQL via Python ETL scripts. Power BI connects to Azure SQL via DirectQuery for live reporting. The Claude API integration calls claude-sonnet for batch classification of review text, with results written back to the database.",
    },
  },
  {
    id: "kanji",
    title: "Kanji Practice Web App",
    type: "tool",
    typeLabel: "Web Tool · ML",
    date: "2026",
    thumb: "thumb-rose",
    thumbIcon: "漢",
    thumbLabel: "ONNX · MobileNetV3",
    desc: "Mobile-first PWA for JLPT N5–N1 kanji writing practice (2,230 characters) with on-device CNN recognition — no backend required.",
    tags: ["JavaScript", "Python", "PyTorch", "ONNX", "MobileNetV3"],
    links: { demo: "https://kanji-practice.netlify.app" },
    metrics: [
      { key: "Characters", val: "2,230" },
      { key: "Training Images", val: "630K+" },
      { key: "Backend", val: "None (client-side)" },
    ],
    detail: {
      overview: "A progressive web app for serious kanji study — covering all JLPT levels from N5 to N1. The entire ML inference pipeline runs in the browser via ONNX Runtime Web, so there's no server cost and it works offline after first load.",
      highlights: [
        "Trained a MobileNetV3-Small CNN on 630K+ synthetic images generated from KanjiVG stroke data; exported to ONNX and served client-side via ONNX Runtime Web",
        "Dual-recognition engine combining DTW stroke-order matching and CNN inference, with score fusion and self-assessment fallback for ambiguous cases",
        "Stroke-by-stroke animation with real-time feedback so learners can compare their attempt side-by-side with the correct form",
        "Per-level progress tracking across all 5 JLPT tiers (N5 → N1)",
        "Web Audio API sound effects for correct/incorrect feedback",
        "Mobile-first PWA deployed on Netlify — installable, works offline",
      ],
      techDetail: "CNN trained in PyTorch on synthetically generated kanji images (font variations, noise augmentation, stroke distortion) from KanjiVG vector data. Exported to ONNX and loaded in-browser with onnxruntime-web. DTW stroke matching runs against reference stroke sequences stored as JSON. No backend — all inference, progress state, and assets are client-side.",
      extraImage: { src: "images/kanji-curve.png", caption: "Training loss & accuracy curve — MobileNetV3-Small on 630K synthetic kanji images" },
    },
  },
  {
    id: "tip-calculator",
    title: "Tip Calculator",
    type: "tool",
    typeLabel: "Web Tool",
    date: "2026",
    thumb: "thumb-amber",
    thumbIcon: "🧾",
    thumbLabel: "HTML · CSS · JS",
    desc: "Mobile-first bill splitter with GPS-based local tax rates, split-by-dish mode, pre/post-tax tip comparison, bilingual UI (EN/中), and one-tap share to group chats.",
    tags: ["HTML", "CSS", "Vanilla JavaScript", "Git", "Cursor AI"],
    links: { demo: "https://aatipscalc.vercel.app", blog: "https://theparnassus.xyz/2026/05/08/tip-calculator-for-splitting-bills/" },
    metrics: [
      { key: "Tax Lookup", val: "GPS + Nominatim" },
      { key: "Languages", val: "EN / 中文" },
      { key: "Bundle", val: "Zero deps" },
    ],
    detail: {
      overview: "Built to solve a real annoyance: nobody at the table agrees on how to split tax and tip, and most calculator apps are clunky on mobile. Single-file vanilla HTML/CSS/JS — no framework, no build step, accelerated with Cursor AI.",
      highlights: [
        "Split evenly or by dish; shared items split among a selectable subset of people",
        "GPS → Nominatim → local restaurant tax rate, with manual state selector fallback",
        "Pre-tax vs post-tax tip comparison with savings delta",
        "Copy bill as plain text for group chats; screenshot export",
        "Bilingual (Chinese/English) based on device default",
        "Mobile-first, localStorage persistence, one-tap reset",
      ],
      techDetail: "Single index.html with vanilla JS — no React, no build pipeline. Tax lookup chains the Geolocation API → Nominatim reverse geocoding → a state-to-rate table. Deployed on Vercel. GoatCounter added for cookie-free, privacy-respecting analytics.",
    },
  },
  {
    id: "spotify",
    title: "AI Spotify Playlist Organizer",
    type: "tool",
    typeLabel: "Tool · AI",
    date: "2024",
    thumb: "thumb-green",
    thumbIcon: "🎵",
    thumbLabel: "OpenAI · Spotipy",
    desc: "Python tool that uses OpenAI API to analyze and auto-categorize Spotify playlists by language, vocal type, and genre — 77.6% faster with multi-threading. Documented in a 3-part blog series.",
    tags: ["Python", "OpenAI API", "Spotipy", "ThreadPoolExecutor"],
    links: { blog: "https://theparnassus.xyz/2024/11/24/built-a-spotify-playlist-organizer-using-openai-and-python/", github: "https://github.com/jfan4926/AI_Playlist_Organizer" },
    metrics: [
      { key: "Speed Improvement", val: "77.6%" },
      { key: "Processing Time", val: "1 min / 30 songs" },
      { key: "Classification Axes", val: "3" },
    ],
    detail: {
      overview: "Born from wanting to actually organize a personal Spotify library without doing it by hand. The tool authenticates with Spotify, pulls tracks from any playlist, sends each song to OpenAI for classification, then automatically creates and populates sub-playlists — e.g. 'language-japanese', 'vocal-female', 'genre-pop'. Documented across a 3-part blog series.",
      highlights: [
        "5-step pipeline: Spotify OAuth → track fetch → OpenAI classification → dynamic playlist creation → execution",
        "Prompt engineering for multi-axis classification by language, vocal type, and genre in a single API call",
        "77.6% speed improvement via ThreadPoolExecutor — 30-song playlist down from 5 minutes to 1 minute",
        "Debugged breaking change in OpenAI Python library: response.choices[0].message.content vs. direct indexing",
        "Iterated on prompts to improve accuracy — Japanese detection worked well out of the box; English disambiguation required refinement",
        "Discovered genre and language boundaries are genuinely fuzzy: city pop sits between jazz, pop, and Japanese — a hard case for any classifier",
      ],
      techDetail: "Python script using Spotipy for Spotify OAuth and API calls. Each track's name and artist are sent to the OpenAI chat completions endpoint with a structured prompt. ThreadPoolExecutor runs API calls concurrently with a thread-safe dictionary collecting results. Playlist creation and track insertion use Spotipy's playlist_add_items API.",
    },
  },
  {
    id: "cv-artist",
    title: "Artwork Artist Identification",
    type: "academic",
    typeLabel: "Academic · CV",
    date: "2023",
    thumb: "thumb-rose",
    thumbIcon: "🖼️",
    thumbLabel: "PyTorch · ViT · ResNet",
    desc: "Group project automating art attribution with deep learning — benchmarking 6 architectures (AlexNet, VGG, ResNet, MobileNet, custom CNN, and Vision Transformer) on painting classification.",
    tags: ["Python", "PyTorch", "ResNet", "Vision Transformer", "CNN"],
    links: { blog: "https://theparnassus.xyz/2023/11/14/previous-cv-group-project/" },
    metrics: [
      { key: "Models Compared", val: "6" },
      { key: "Domain", val: "Computer Vision" },
      { key: "Type", val: "Group Project" },
    ],
    detail: {
      overview: "A computer vision course project tackling a task that normally requires deep art history expertise: identifying an artist solely from the visual style of their paintings. Trained and compared six architectures to understand how CNNs and Vision Transformers differ in learning painterly features.",
      highlights: [
        "Custom CNN baseline: 5 conv blocks each with two Conv2D + ReLU layers, max pooling, and batch normalization, followed by an MLP classifier",
        "Benchmarked AlexNet, VGG, ResNet, and MobileNet with ImageNet pretrained weights and fine-tuning",
        "Vision Transformer: patch embedding with positional encoding → multi-layer transformer encoder with self-attention → classification head",
        "CNNs learn spatially-local brushwork features; ViT learns patch-wise global composition — both relevant to style attribution",
        "Compared architectures across accuracy, parameter count, and training time",
      ],
      techDetail: "Built with PyTorch. All CNN models initialized with ImageNet pretrained weights and fine-tuned on the painting dataset. ViT implemented from components (patch embedding, multi-headed self-attention, residual blocks). Training on GPU with data augmentation (random crop, flip, color jitter) to reduce overfitting on the relatively small art dataset.",
    },
  },
  {
    id: "dl-recipe",
    title: "Dish → Ingredient Prediction",
    type: "academic",
    typeLabel: "Academic · NLP",
    date: "2023",
    thumb: "thumb-teal",
    thumbIcon: "🍜",
    thumbLabel: "PyTorch · Transformer · GRU",
    desc: "Seq2Seq project predicting dish ingredients from dish names — GRU vs. Transformer with multi-headed attention, trained on 494K recipes, evaluated with Jaccard similarity.",
    tags: ["Python", "PyTorch", "Transformer", "GRU", "Seq2Seq", "NLP"],
    links: { blog: "https://theparnassus.xyz/2023/11/07/previous-dl-group-project-1/" },
    metrics: [
      { key: "Training Data", val: "494,963 recipes" },
      { key: "Perplexity", val: "~14 @ epoch 10" },
      { key: "Eval Metric", val: "Jaccard Similarity" },
    ],
    detail: {
      overview: "Framed recipe generation as a sequence-to-sequence problem: given only a dish name, predict its ingredient list. Trained on a 494K-recipe Kaggle dataset and evaluated on both seen dishes and novel names never in training — testing whether the model learned genuine culinary patterns.",
      highlights: [
        "Preprocessing pipeline: tokenization, padding/truncating, and frequency-based normalization ('onion' and 'onions' → same token)",
        "GRU-based encoder-decoder with attention; Transformer with multi-headed self-attention, embedding size 256, 3 attention heads, batch size 100",
        "Evaluation via Jaccard Similarity: J = |G ∩ P| / |G ∪ P| — measures overlap between predicted and ground-truth ingredient sets",
        "Perplexity dropped to ~14 after 10 epochs on the Transformer model",
        "Greedy decoding outperformed top-20 candidate filtering — restricting the search space hurt more than it helped",
        "Qualitative results: 'chocolate cookies' → butter, sugar, eggs, flour ✓ — but 'apple chicken' produced cinnamon/nutmeg three times, highlighting the duplicate generation problem",
        "Duplicate ingredient generation identified as the key failure mode; planned fix: constrained decoding to prevent repeated tokens",
      ],
      techDetail: "Built from scratch in PyTorch — no HuggingFace. Word-level tokenization with a shared source/target vocabulary. Transformer trained with a learning rate warmup schedule. GRU trained with teacher forcing; inference uses greedy decoding feeding outputs sequentially back as inputs.",
    },
  }
];
