const PROJECTS = [
  {
    id: "nyc311",
    title: "NYC 311 Complaint Analytics",
    type: "da",
    typeLabel: "Data Analysis · ML",
    date: "2026",
    thumb: "thumb-blue",
    thumbIcon: "🗽",
    thumbLabel: "dbt · DuckDB · XGBoost",
    desc: "End-to-end analytics platform on 499K+ NYC 311 service requests — geospatial heatmaps, Prophet forecasting, XGBoost classification, and a multi-turn LLM Text-to-SQL agent.",
    tags: ["Python", "dbt", "DuckDB", "XGBoost", "LLaMA 3.1", "Streamlit"],
    links: { demo: "https://nyc311-analytics-jfan.streamlit.app/", github: "https://github.com/jfan4926" },
    metrics: [
      { key: "Records", val: "499K+" },
      { key: "XGBoost AUC", val: "0.96" },
      { key: "Forecast Horizon", val: "4 months" },
    ],
    detail: {
      overview: "A full-stack analytics platform built on NYC open data, covering the complete journey from raw ingestion to an interactive Streamlit app. Combines classical ML, time series forecasting, and a conversational AI agent in a single deployment.",
      highlights: [
        "dbt staging-to-marts architecture on DuckDB with automated data quality tests",
        "Interactive geospatial heatmap of complaint density across NYC boroughs",
        "Prophet time series model forecasting 4-month complaint volumes by category",
        "XGBoost classifier (AUC = 0.96) with Optuna tuning, MLflow tracking, Evidently drift monitoring, and SHAP waterfall charts for per-prediction explainability",
        "Similar historical case lookup for real-world context alongside each prediction",
        "Multi-turn LLM Text-to-SQL agent (LLaMA 3.1 · Groq · RAG) with conversation history and follow-up question support",
        "GitHub Actions CI/CD running automated dbt tests and ruff linting on every push",
      ],
      techDetail: "dbt handles all transformations on a DuckDB file — staging models clean raw CSVs, mart models aggregate KPIs. The ML pipeline (XGBoost + Optuna + MLflow) runs independently and persists artifacts for the Streamlit app to load. LLM agent uses RAG over schema docs to translate natural language to SQL at query time.",
    },
  },
  {
    id: "ecommerce",
    title: "E-Commerce Analytics & AI Insights",
    type: "bi",
    typeLabel: "BI / Dashboard · AI",
    date: "2026",
    thumb: "thumb-indigo",
    thumbIcon: "🛒",
    thumbLabel: "Azure · Power BI · Claude",
    desc: "End-to-end analytics pipeline on 100K+ orders — Azure cloud stack, Power BI & Tableau dashboards, Claude API sentiment analysis, and Bayesian A/B testing.",
    tags: ["Python", "SQL", "Azure", "Power BI", "Tableau", "Claude API"],
    links: { demo: "https://e-commerce-analytics-jfan.streamlit.app/", github: "https://github.com/jfan4926" },
    metrics: [
      { key: "GMV Tracked", val: "$15.4M" },
      { key: "Orders", val: "100K+" },
      { key: "Reviews Analyzed", val: "4,500+" },
    ],
    detail: {
      overview: "A cloud-native analytics pipeline for a Brazilian e-commerce dataset, spanning data ingestion through executive dashboards and AI-powered insights. Built to mirror a real-world enterprise BI stack.",
      highlights: [
        "Azure Blob Storage + Azure SQL + star schema data model as the cloud foundation",
        "Power BI dashboards with DAX-based KPI tracking: GMV, delivery SLA, regional satisfaction",
        "Tableau geospatial analysis of customer distribution and regional performance trends",
        "Claude API integration for multilingual review classification and sentiment analysis across 4,500+ Portuguese reviews",
        "Bayesian A/B testing engine using Monte Carlo simulation (50K+ samples) to measure delivery speed impact on satisfaction",
        "Conversational Text-to-SQL AI agent deployed via Streamlit Cloud with GitHub Actions and pytest automation",
      ],
      techDetail: "Data flows from Azure Blob → Azure SQL via Python ETL scripts. Power BI connects to Azure SQL via DirectQuery for live reporting. The Claude API integration calls claude-sonnet for batch classification of review text, with results written back to the database.",
    },
  },
  {
    id: "spotify",
    title: "AI Spotify Playlist Organizer",
    type: "tool",
    typeLabel: "Tool · AI",
    date: "2024",
    thumb: "thumb-green",
    thumbIcon: "🎵",
    thumbLabel: "OpenAI · Spotipy",
    desc: "Python tool that uses OpenAI API to analyze and auto-categorize Spotify playlists by language, vocal type, and genre — 77.6% faster with multi-threading.",
    tags: ["Python", "OpenAI API", "Spotipy", "ThreadPoolExecutor"],
    links: { blog: "https://theparnassus.xyz/2024/11/24/built-a-spotify-playlist-organizer-using-openai-and-python/", github: "https://github.com/jfan4926/AI_Playlist_Organizer" },
    metrics: [
      { key: "Speed Improvement", val: "77.6%" },
      { key: "Processing Time", val: "1 min / 30 songs" },
      { key: "Classification Axes", val: "3" },
    ],
    detail: {
      overview: "A command-line tool that connects to your Spotify account, pulls playlist tracks, and uses GPT to classify each song by language, vocal type, and genre — then automatically creates and populates new organized playlists via the Spotify API. Documented across a 3-part series on my blog.",
      highlights: [
        "OpenAI API prompt engineering for accurate multi-axis classification (language, vocal type, genre)",
        "77.6% processing speed improvement via ThreadPoolExecutor multi-threading with thread-safe data handling",
        "Reduced processing time for a 30-song playlist from 5 minutes to 1 minute",
        "Spotipy integration for OAuth authentication, track fetching, and automated playlist creation",
        "Iterative prompt refinement to improve language detection accuracy across multilingual playlists",
      ],
      techDetail: "Python script using Spotipy for Spotify OAuth and API calls. Each track's metadata is sent to OpenAI's chat completion endpoint with a structured prompt that returns a JSON classification. ThreadPoolExecutor batches API calls concurrently with a thread-safe results dictionary.",
    },
  },
  {
    id: "tip-calculator",
    title: "Tip Calculator",
    type: "tool",
    typeLabel: "Web Tool",
    date: "2026",
    thumb: "thumb-amber",
    thumbIcon: "🧾",
    thumbLabel: "HTML · CSS · JS",
    desc: "Mobile-first bill splitter with GPS-based local tax rates, split-by-dish mode, pre/post-tax tip comparison, bilingual UI (EN/中), and one-tap share to group chats.",
    tags: ["HTML", "CSS", "JavaScript", "Geolocation API", "Nominatim"],
    links: { blog: "https://theparnassus.xyz/2026/05/08/tip-calculator-for-splitting-bills/" },
    metrics: [
      { key: "Tax Lookup", val: "GPS + Nominatim" },
      { key: "Languages", val: "EN / 中文" },
      { key: "Bundle", val: "Zero deps" },
    ],
    detail: {
      overview: "A thoughtful utility app for dining out — designed around the real friction points of splitting a bill in a group. Built mobile-first with zero dependencies and instant load time.",
      highlights: [
        "Split evenly or by dish, with shared items split among a selectable subset of people",
        "GPS → Nominatim → local restaurant tax rate lookup, with manual state selector fallback",
        "Pre-tax vs post-tax tip comparison with savings delta displayed clearly",
        "Copy bill summary as plain text for group chats; screenshot export for sharing",
        "Bilingual UI (Chinese/English) auto-detected from device locale",
        "localStorage persistence across sessions; one-tap reset for a new bill",
      ],
      techDetail: "Pure vanilla HTML/CSS/JS — no build step, no framework, no dependencies. Tax rate lookup chains GPS coordinates through the Nominatim reverse geocoding API to a state → rate lookup table.",
    },
  },
  {
    id: "cv-artist",
    title: "Artwork Artist Identification",
    type: "academic",
    typeLabel: "Academic · CV",
    date: "2023",
    thumb: "thumb-rose",
    thumbIcon: "🖼️",
    thumbLabel: "PyTorch · ViT · ResNet",
    desc: "Group project benchmarking CNN architectures and Vision Transformers for artist classification from painting images — comparing AlexNet, VGG, ResNet, MobileNet, and ViT.",
    tags: ["Python", "PyTorch", "ResNet", "Vision Transformer", "CNN"],
    links: { blog: "https://theparnassus.xyz/2023/11/14/previous-cv-group-project/" },
    metrics: [
      { key: "Type", val: "Group Project" },
      { key: "Domain", val: "Computer Vision" },
      { key: "Models Compared", val: "5" },
    ],
    detail: {
      overview: "A computer vision course group project exploring whether neural networks can learn to identify artists from the visual style of their paintings. Trained and evaluated five architectures to find the best approach for fine-grained artwork classification.",
      highlights: [
        "Dataset: painting images labeled by artist, preprocessed and augmented for training",
        "Benchmarked AlexNet, VGG, ResNet, MobileNet across accuracy, training time, and parameter efficiency",
        "Implemented Vision Transformer (ViT) and compared against CNN baselines",
        "Analysis of which visual features (brushwork, color palette, composition) each model weighted most heavily",
      ],
      techDetail: "Built with PyTorch. Transfer learning from ImageNet pretrained weights for all CNN models. ViT implemented from scratch and with pretrained weights. Training run on GPU with mixed-precision to manage compute.",
    },
  },
  {
    id: "dl-recipe",
    title: "Dish → Ingredient Prediction",
    type: "academic",
    typeLabel: "Academic · NLP",
    date: "2023",
    thumb: "thumb-teal",
    thumbIcon: "🍜",
    thumbLabel: "PyTorch · Transformer · GRU",
    desc: "Seq2Seq deep learning project predicting dish ingredients from dish names — comparing RNN/GRU and Transformer with multi-headed attention, trained on 500K+ recipes.",
    tags: ["Python", "PyTorch", "Transformer", "GRU", "Seq2Seq", "NLP"],
    links: { blog: "https://theparnassus.xyz/2023/11/07/previous-dl-group-project-1/" },
    metrics: [
      { key: "Type", val: "Group Project" },
      { key: "Training Data", val: "500K+ recipes" },
      { key: "Domain", val: "NLP · Seq2Seq" },
    ],
    detail: {
      overview: "A deep learning course group project framing recipe generation as a sequence-to-sequence problem: given a dish name, predict the ingredients. Trained on a large Kaggle recipe dataset and evaluated both on known dishes and novel creations.",
      highlights: [
        "Dataset: ~500K recipes from Kaggle, preprocessed into dish name → ingredient list pairs",
        "Implemented RNN-based Seq2Seq with GRU encoder-decoder and attention mechanism",
        "Implemented Transformer with multi-headed self-attention and positional encoding",
        "Evaluated on both seen dishes (reconstruction) and novel dish names not in the training set",
        "Compared models on BLEU score and qualitative ingredient plausibility",
      ],
      techDetail: "Built with PyTorch from scratch — no HuggingFace. Tokenization at the word level with shared vocabulary. Transformer trained with learning rate warmup schedule. GRU model trained with teacher forcing and evaluated with greedy decoding.",
    },
  },
];
